import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight, ArrowRight, Menu, X, Globe2, ShoppingBag, PanelsTopLeft, Cloud, Headset, ShieldCheck, Code2, Layers3, Send} from 'lucide-react';
import './styles.css';
const services=[
  {icon:Globe2,title:'Web development',detail:'Business websites and digital experiences that make your work clear and accessible.',tags:'Websites · Landing pages · Maintenance'},
  {icon:ShoppingBag,title:'E-commerce',detail:'Thoughtful online storefronts that help customers discover and buy your products.',tags:'Catalogues · Checkout planning · Store UX'},
  {icon:PanelsTopLeft,title:'Custom web applications',detail:'Purpose-built tools for workflows that need more than an off-the-shelf solution.',tags:'Platforms · Dashboards · Portals'},
  {icon:Cloud,title:'Cloud & maintenance',detail:'Practical support for deployment, updates and keeping your digital presence running.',tags:'Deployment · Updates · Support'},
  {icon:Headset,title:'IT consulting',detail:'Clear guidance on choosing the right technology for your organisation.',tags:'Planning · Systems · Digital strategy'}
];
const steps=['Discover','Design','Build','Deploy','Support'];
function App(){const [menuOpen,setMenuOpen]=useState(false);const [copied,setCopied]=useState(false);
  const nav=[['Work','#work'],['Services','#services'],['Process','#process'],['About','#about'],['Contact','#contact']];
  const close=()=>setMenuOpen(false);
  const copyBrief=async()=>{try{await navigator.clipboard.writeText('Hello Tech & GUARD,\n\nMy name is: \nMy organisation: \nI need help with: \nProject details: \nPreferred contact: ');setCopied(true);setTimeout(()=>setCopied(false),3000)}catch{setCopied(false)}};
  return <><a className="skip" href="#main">Skip to content</a><header className="site-header"><a className="brand" href="#top" onClick={close} aria-label="Tech and GUARD home"><span className="brand-mark">T<span>&</span>G</span><span className="brand-name">TECH <em>&</em> GUARD<small>DIGITAL SOLUTIONS</small></span></a><nav className={menuOpen?'nav open':'nav'} aria-label="Main navigation">{nav.map(([label,href])=><a onClick={close} href={href} key={label}>{label}</a>)}<a className="nav-cta" href="#contact" onClick={close}>Start a project <ArrowUpRight size={15}/></a></nav><button className="menu-toggle" onClick={()=>setMenuOpen(!menuOpen)} aria-label={menuOpen?'Close menu':'Open menu'} aria-expanded={menuOpen}>{menuOpen?<X/>:<Menu/>}</button></header>
  <main id="main"><section id="top" className="hero"><div className="hero-glow"/><div className="grid-haze"/><div className="container hero-inner"><div className="eyebrow"><span className="pulse"/> SOUTH AFRICAN DIGITAL STUDIO <span className="line"/> 01 / 05</div><h1>ARCHITECTING<br/><span>DIGITAL</span><br/>RESILIENCE<span className="period">.</span></h1><div className="hero-bottom"><p>We design, build and support practical digital solutions that help businesses work smarter and grow with confidence.</p><div className="actions"><a className="button primary" href="#contact">Start a project <ArrowUpRight size={18}/></a><a className="button ghost" href="#work">Explore our work <ArrowRight size={18}/></a></div></div><div className="hero-index">TECHNOLOGY WITH PURPOSE <span>SCROLL TO EXPLORE ↓</span></div></div><div className="hero-orbit" aria-hidden="true"><div className="orbit a"/><div className="orbit b"/><div className="orbit c"/><div className="orbit-core">T<span>&</span>G</div></div></section>
  <section className="statement container"><span className="label">/ OUR POINT OF VIEW</span><p>Good technology makes the complex feel <em>simple.</em> We build digital experiences around real people, real work and real opportunities.</p></section>
  <section id="services" className="section services"><div className="container"><div className="section-heading"><div><span className="label">01 / EXPERTISE</span><h2>Technology built<br/>around <span>your business.</span></h2></div><p>From the first idea to the next iteration, we focus on solutions that are useful, considered and built to evolve.</p></div><div className="service-grid">{services.map((s,i)=><article className="service" key={s.title}><div className="service-top"><s.icon size={26} strokeWidth={1.5}/><span>0{i+1}</span></div><h3>{s.title}</h3><p>{s.detail}</p><small>{s.tags}</small></article>)}</div></div></section>
  <section id="work" className="section work"><div className="container"><div className="section-heading"><div><span className="label">02 / SELECTED WORK</span><h2>From concept to<br/><span>working technology.</span></h2></div><p>A look at our own platforms and products in development. Project status is shown clearly below.</p></div><div className="projects"><article className="project project-blue"><div className="project-copy"><span className="project-num">01 / EDUCATION TECHNOLOGY</span><h3>SmartBridge<br/>FET<span>.</span></h3><p>An education platform concept connecting learners with tutoring and learning opportunities.</p><div className="pills"><span>Platform design</span><span>Education</span><span>In development</span></div></div><div className="project-art smart" aria-hidden="true"><div className="mock-window"><div className="mock-bar"><i/><i/><i/></div><div className="mock-side"/><div className="mock-content"><div className="mock-title"/><div className="mock-line"/><div className="mock-cards"><b/><b/><b/></div></div></div></div></article><article className="project project-dark"><div className="project-copy"><span className="project-num">02 / DIGITAL COMMERCE</span><h3>Tech & GUARD<br/>Store<span>.</span></h3><p>Our product storefront for technology accessories and everyday essentials, developed as an ongoing commerce project.</p><div className="pills"><span>E-commerce</span><span>Customer experience</span><span>Own project</span></div><a className="text-link" href="https://tech-and-guard.base44.app" target="_blank" rel="noopener noreferrer">Visit the store <ArrowUpRight size={17}/></a></div><div className="project-art store" aria-hidden="true"><div className="store-card"><div className="store-object"/><div className="store-caption"/><div className="store-caption short"/></div><div className="store-card behind"/></div></article></div><p className="work-note">More experiments and case studies will be added as they are ready to share.</p></div></section>
  <section id="process" className="section process"><div className="container"><div className="section-heading"><div><span className="label">03 / APPROACH</span><h2>From problem<br/>to <span>solution.</span></h2></div><p>A straightforward process that makes room for discovery, careful execution and ongoing improvement.</p></div><div className="steps">{steps.map((s,i)=><div className="step" key={s}><span>0{i+1}</span><h3>{s}</h3><ArrowUpRight size={20}/></div>)}</div></div></section>
  <section id="about" className="section about"><div className="container about-grid"><div><span className="label">04 / ABOUT US</span><h2>Technology<br/>with <span>purpose.</span></h2></div><div className="about-copy"><p>Tech & GUARD (Pty) Ltd is a South African technology company focused on practical digital solutions for businesses, organisations and entrepreneurs.</p><p>We bring design and development together to turn ideas and operational challenges into digital tools people can actually use.</p><div className="values"><div><ShieldCheck/><span>Practical by design</span></div><div><Layers3/><span>Made to evolve</span></div><div><Code2/><span>Built with care</span></div></div></div></div></section>
  <section id="contact" className="section contact"><div className="container contact-inner"><span className="label">05 / GET IN TOUCH</span><h2>Have a problem<br/>worth <span>solving?</span></h2><p>Tell us what you are trying to build, improve or solve. Start with a short project brief and we can take it from there.</p><button className="button primary" onClick={copyBrief}>Copy a project brief <Send size={17}/></button><span className="copy-status" role="status">{copied?'Brief copied. Paste it into your preferred message or email.':'A contact address and enquiry form will be added when confirmed.'}</span></div></section></main><footer><div className="container footer-inner"><a className="brand footer-brand" href="#top"><span className="brand-mark">T<span>&</span>G</span><span className="brand-name">TECH <em>&</em> GUARD<small>DIGITAL SOLUTIONS</small></span></a><span>© {new Date().getFullYear()} Tech & GUARD (Pty) Ltd.</span><a href="#top">Back to top ↑</a></div></footer></>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
